---
apiVersion: database.azure.crossplane.io/v1beta1
kind: PostgreSQLServer
metadata:
  name: psql-west
  labels:
    region: "us-west"
spec:
  forProvider:
    administratorLogin: myadmin
    resourceGroupNameRef:
      name: aks-west-rg
    location: West US 2
    sslEnforcement: Disabled
    version: "9.6"
    sku:
      # Note that Basic servers do not support virtual network rules
      tier: GeneralPurpose
      capacity: 2
      family: Gen5
    storageProfile:
      storageMB: 20480
  writeConnectionSecretsToRef:
    namespace: crossplane-system
    name: psql-west
  providerRef:
    name: azure-provider
  reclaimPolicy: Delete
