---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  labels:
    provider: aws
  name: eks-west-cluster-iamrolepolicyattachment
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    policyArnRef:
      name: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    roleNameRef:
      name: eks-west-iamrole
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  labels:
    provider: aws
  name: eks-west-service-iamrolepolicyattachment
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSServicePolicy
    policyArnRef:
      name: arn:aws:iam::aws:policy/AmazonEKSServicePolicy
    roleNameRef:
      name: eks-west-iamrole
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
