apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  name: sql-west
spec:
  classSelector:
    matchLabels:
      name: rds-us-west
  engineVersion: "5.7"
  writeConnectionSecretToRef:
    name: sql-west
