---
apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: west-akscluster
  labels:
    region: "west"
spec:
  resourceGroupNameRef:
    name: aks-west-rg
  vnetSubnetIDRef:
    name: aks-west-sb
  location: West US 2
  version: "1.17.11"
  nodeCount: 1
  nodeVMSize: Standard_B2s
  dnsNamePrefix: crossplane-aks
  disableRBAC: false
  providerRef:
    name: azure-provider
  reclaimPolicy: Delete
  writeConnectionSecretsToNamespace: crossplane-system
