---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    provider: aws
  name: eks-west-securitygroup
spec:
  forProvider:
    region: us-west-2
    vpcIdRef:
      name: eks-west-vpc
    groupName: eks-west-sg
    description: Cluster communication with worker nodes
  providerRef:
    name: aws-provider
