apiVersion: network.aws.crossplane.io/v1alpha3
kind: SecurityGroup
metadata:
  labels:
    provider: aws
  name: rds-west-securitygroup
spec:
  description: security group for us-west rds
  groupName: rds-west-sg
  ingress:
  - cidrBlocks:
    - cidrIp: 0.0.0.0/0
      description: all ips
    fromPort: 3306
    protocol: tcp
    toPort: 3306
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  vpcIdRef:
    name: eks-west-vpc
