---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    provider: aws
  name: rds-west-securitygroup
spec:
  forProvider:
    region: us-west-2
    vpcIdRef:
      name: eks-west-vpc
    groupName: rds-west-sg
    description: security group for us-west rds
    ingress:
      - fromPort: 3306
        ipProtocol: tcp
        toPort: 3306
        ipRanges:
          - cidrIp: 0.0.0.0/0
  providerRef:
    name: aws-provider
