---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  labels:
    provider: aws
  name: eks-west-internetgateway
spec:
  forProvider:
    region: us-west-2
    vpcIdRef:
      name: eks-west-vpc
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
