---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  labels:
    provider: aws
  name: eks-west-subnet1
spec:
  forProvider:
    #region: us-west-2a
    availabilityZone: us-west-2a
    cidrBlock: 192.168.64.0/18
    vpcIdRef:
      name: eks-west-vpc
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  labels:
    provider: aws
  name: eks-west-subnet2
spec:
  forProvider:
    availabilityZone: us-west-2b
    #region: us-west-2b
    cidrBlock: 192.168.128.0/18
    vpcIdRef:
      name: eks-west-vpc
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  labels:
    provider: aws
  name: eks-west-subnet3
spec:
  forProvider:
    availabilityZone: us-west-2c
    #region: us-west-2c
    cidrBlock: 192.168.192.0/18
    vpcIdRef:
      name: eks-west-vpc
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
