apiVersion: network.aws.crossplane.io/v1alpha3
kind: Subnet
metadata:
  labels:
    provider: aws
  name: eks-west-subnet1
spec:
  availabilityZone: us-west-2a
  cidrBlock: 192.168.64.0/18
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  vpcIdRef:
    name: eks-west-vpc
---
apiVersion: network.aws.crossplane.io/v1alpha3
kind: Subnet
metadata:
  labels:
    provider: aws
  name: eks-west-subnet2
spec:
  availabilityZone: us-west-2b
  cidrBlock: 192.168.128.0/18
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  vpcIdRef:
    name: eks-west-vpc
---
apiVersion: network.aws.crossplane.io/v1alpha3
kind: Subnet
metadata:
  labels:
    provider: aws
  name: eks-west-subnet3
spec:
  availabilityZone: us-west-2c
  cidrBlock: 192.168.192.0/18
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  vpcIdRef:
    name: eks-west-vpc
