apiVersion: network.azure.crossplane.io/v1alpha3
kind: VirtualNetwork
metadata:
  name: aks-west-vn
spec:
  resourceGroupNameRef:
    name: aks-west-rg
  location: West US 2
  properties:
    addressSpace:
      addressPrefixes:
        - 10.2.0.0/16
  reclaimPolicy: Delete
  providerRef:
    name: azure-provider
